### ISSUE TITLE
Add interpolate-size to css defaults

### ISSUE THREAD

**Issue by grantcodes** [grantcodes/ui#11]
As seen on https://utilitybend.com/blog/added-to-my-css-reset-interpolate-size-the-quality-of-life-feature-we-all-wanted-at-some-point, I'd like to add this to my default css.

```css
:root {
  @supports (interpolate-size: allow-keywords) {
    interpolate-size: allow-keywords;
  }
}
```
